name: Update Risk Matrix Data

on:
  schedule:
    - cron: '30 22 * * 1-5'  # 工作日北京时间 6:30
  workflow_dispatch:  # 手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Setup V2Ray Proxy for Data Collection
        run: |
          # 下载并安装 V2Ray
          curl -L -o v2ray-linux.zip https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip v2ray-linux.zip -d v2ray
          chmod +x v2ray/v2ray
          
          # 创建 V2Ray 配置文件
          cat > v2ray/config.json << EOF
          {
            "inbounds": [
              {
                "port": 1080,
                "protocol": "socks",
                "settings": {
                  "auth": "noauth",
                  "udp": true
                }
              }
            ],
            "outbounds": [
              {
                "protocol": "vmess",
                "settings": {
                  "vnext": [
                    {
                      "address": "${{ secrets.VMESS_HOST }}",
                      "port": ${{ secrets.VMESS_PORT }},
                      "users": [
                        {
                          "id": "${{ secrets.VMESS_UUID }}",
                          "alterId": ${{ secrets.VMESS_ALTERID }},
                          "security": "auto"
                        }
                      ]
                    }
                  ]
                },
                "streamSettings": {
                  "network": "${{ secrets.VMESS_NETWORK }}",
                  "security": "none"
                }
              }
            ]
          }
          EOF
          
          # 启动 V2Ray （使用正确的命令格式）
          ./v2ray/v2ray run -config v2ray/config.json > v2ray.log 2>&1 &
          V2RAY_PID=$!
          echo "V2RAY_PID=$V2RAY_PID" >> $GITHUB_ENV
          
          # 等待 V2Ray 启动
          echo "⏱️ 等待V2Ray启动..."
          sleep 10
          
          # 检查V2Ray进程是否还在运行
          if ps -p $V2RAY_PID > /dev/null; then
              echo "✅ V2Ray进程运行正常 (PID: $V2RAY_PID)"
          else
              echo "❌ V2Ray进程已退出，查看日志:"
              cat v2ray.log
              exit 1
          fi
          
          # 测试代理连接
          echo "🔄 测试代理连接..."
          for i in {1..3}; do
              if curl --socks5 127.0.0.1:1080 --connect-timeout 10 https://httpbin.org/ip; then
                  echo "✅ 代理连接测试成功"
                  break
              else
                  echo "⚠️ 第${i}次代理测试失败，等待5秒后重试..."
                  sleep 5
                  if [ $i -eq 3 ]; then
                      echo "❌ 代理连接测试失败，查看V2Ray日志:"
                      cat v2ray.log
                      # 不退出，继续执行数据收集
                  fi
              fi
          done

      - name: Create data directory
        run: |
          mkdir -p data

      - name: Calculate Risk Matrix Data (with proxy)
        env:
          USE_PROXY: "true"
          PROXY_HOST: "127.0.0.1"
          PROXY_PORT: "1080"
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python scripts/risk_matrix_calculator.py

      - name: Stop V2Ray Proxy
        run: |
          if [ ! -z "$V2RAY_PID" ]; then
            kill $V2RAY_PID 2>/dev/null || true
            echo "🛑 V2Ray代理已停止"
          fi

      - name: Upload to Tencent Cloud COS (direct connection)
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          COS_BUCKET_NAME: ${{ secrets.COS_BUCKET_NAME }}
          COS_REGION: ${{ secrets.COS_REGION }}
          USE_PROXY: "false"
        run: |
          python scripts/data_uploader.py

      - name: Archive logs and data
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: execution-logs
          path: |
            data/
            v2ray.log
          retention-days: 7
